packages:
  # product plugins
  - bot-core
  - bot-suite
  - kook
  - milky
  - telegram
  - plugins/**
  # upstream (thin vendor: vendor/pluxel-template/{packages,plugins,agents})
  - vendor/pluxel-template/packages/**
  - vendor/pluxel-template/plugins/**
  - '!vendor/pluxel-template/plugins/native/napi-rs/*__*'

public-hoist-pattern:
  - '@pluxel/core'
  - '@pluxel/hmr'
